name-template: v$RESOLVED_VERSION
tag-template: v$RESOLVED_VERSION
categories:
  - title: 🚀 Features
    labels:
      - enhancement
      - feature
  - title: 🐛 Bug Fixes
    labels:
      - bug
      - fix
  - title: 🧰 Maintenance
    labels: 
      - maintenance
      - chore
change-template: - $TITLE @$AUTHOR (#$NUMBER)
change-title-escapes: \<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
autolabeler:
  - label: documentation
    files:
      - '*.md'
  - label: fix
    branch:
      - '/fix\/.+/'
  - label: enhancement
    branch:
      - '/feature\/.+/'
  - label: maintenance
    branch:
      - '/maintenance\/.+/'
version-resolver:
  major:
    labels:
      - breaking-change
  minor:
    labels:
      - enhancement
  patch:
    labels:
      - fix
      - maintenance
  default: minor 
template: |
  ## Changes

  $CHANGES
