name: Auto Labeler

on:
  workflow_call:

jobs:
 auto-labeler:
   runs-on: ubuntu-latest
   steps:
     - uses: release-drafter/release-drafter@v5
       with:
         disable-releaser: true
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
