name: CI

on:
  workflow_call:

permissions:
  contents: write
  deployments: write
  id-token: write    
   
jobs:     
  ci:
    name: Check, Buid, Test and Synthesize
    runs-on: ubuntu-latest
        
    steps:    
      - name: Checkout
        uses: actions/checkout@v3
                  
      - name: Setup .NET 6 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x
                  
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Check for vulnerabilities
        uses: snyk/actions/dotnet@master
        with:
          args: --all-projects --policy-path=.snyk --show-vulnerable-paths=all
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}        
      
      - name: Check code formatting
        run: dotnet format --no-restore --verify-no-changes
        
      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner
        
      - name: SonarScanner begin
        run: dotnet sonarscanner begin /o:efteling /k:efteling_${{ github.repository }} /d:sonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Build
        run: dotnet build --configuration Release --no-restore -warnaserror

      - name: Test
        run: dotnet test --configuration Release --no-build dotnet test --settings coverlet.runsettings --logger:trx --filter "FullyQualifiedName~UnitTests|FullyQualifiedName~Component"

      - name: SonarScanner end
        run: dotnet sonarscanner end /d:sonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Install CDK
        run: npm install aws-cdk -g

      - name: Install AWS lambda tools
        run:  dotnet tool install -g Amazon.Lambda.Tools

      - name: Synthesize
        run: cdk synth --quiet --ci

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: cdk.out
          path: cdk.out        
        
    outputs:
      SNYK: ${{ env.artifact-build-info }}        
